import react from "react";
import "./404.css"

function ErrorPage() {
      return(

            <div className="errorPage">

                        <h1 className="textHead">
                              Page Not Found
                        </h1>
                        <img src="https://res.cloudinary.com/durpirilj/image/upload/v1640551605/undraw_location_search_re_ttoj_b81ya0.svg" alt="logo" />

            </div>

      )
}

export default ErrorPage;
